server:
  port: 9521
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    instance-id: zuul-9521
spring:
  application:
    name: gateway-zuul
zuul:
  ignored-services: provider
  routes:
    provider:
      serviceId: provider
      path: /abc/**
