server:
  port: 7003
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
       defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
  instance:
    hostname: eureka7003
    prefer-ip-address: false
