server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    instance-id: order_provider_8081 #微服务名
    prefer-ip-address: true #访问时ip显示
spring:
  application:
    name: order_provider
info:
  app.name: cloud
  company.name: tianjian