server:
  port: 7001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
       defaultZone: http://eureka7001:${server.port}/eureka
  instance:
    hostname: eureka7001
