server:
  port: 7002
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
       defaultZone: http://eureka7001:7001/eureka,http://eureka7003:7003/eureka
  instance:
    hostname: eureka7002
    prefer-ip-address: false
