server:
  port: 7003
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
       defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    hostname: eureka7003
    prefer-ip-address: false
