server:
  port: 7001
eureka:
  client:
    registerWithEureka: false #false表示自己是注册中心，不向注册中心注册自己
    fetchRegistry: false #
    service-url:
       defaultZone: http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    hostname: eureka7001 #eureka服务端的实例名称
    prefer-ip-address: false
